services:
  postgres:
    container_name: postgres-evals
    image: postgres:15.4
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
      - ./.docker/scripts/postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASES=evals_development,evals_test

  evals:
    build:
      context: ../../..
      dockerfile: Roo-Code/packages/evals/Dockerfile
    container_name: roo-evals
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/evals_development
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    volumes:
      - /tmp:/tmp  # For IPC sockets
    command: pnpm cli --exercise two-bucket --include javascript
